[OT294-70]-Endpoint Creación Testimonios
alkemyTech/OT294-server pull request #62
Opened 2022-09-30 22:18 UTC by JtabaresH

https://alkemy-labs.atlassian.net/browse/OT294-70

Ruta en app
![image](https://user-images.githubusercontent.com/71291097/193363821-50f6122d-1629-46ad-8e18-6142f0bacf29.png)

Endpoint crear testimonios
![image](https://user-images.githubusercontent.com/71291097/193363866-42a88be1-7790-4d1f-9111-e5470c02599a.png)

Controlador crear testimonios
![image](https://user-images.githubusercontent.com/71291097/193363890-52d74ebd-4684-4d3c-9d0d-0eadcc739580.png)

2022-09-30 22:43 UTC, JtabaresH commented
![image](https://user-images.githubusercontent.com/71291097/193365975-9ec1e05f-8b05-4874-b299-62a55d4636af.png)

2022-10-02 23:31 UTC, FerLeiva requested changes

2022-10-02 23:31 UTC, FerLeiva commented on controllers/testimonials.controller.js
> +    res.status(201).json({
Es mejor si lo manejas con un try - catch para capturar los errores

2022-10-03 17:42 UTC, FerLeiva approved these changes

2022-10-03 17:42 UTC, merged