[OT294-34]-Endpoint de Eliminar usuario
alkemyTech/OT294-server pull request #67
Opened 2022-10-01 01:48 UTC by opolinad

Jira URL: https://alkemy-labs.atlassian.net/jira/software/c/projects/OT294/boards/388?modal=detail&selectedIssue=OT294-34&quickFilter=781

![image](https://user-images.githubusercontent.com/92406653/193378357-929d8411-6869-4576-bf97-d10bb1f7b455.png)

2022-10-03 17:29 UTC, FerLeiva requested changes

2022-10-03 17:29 UTC, FerLeiva commented on controllers/organization.controller.js
> +    console.log("Entra");
Quitar console.log antes de hacer PRs

2022-10-03 17:29 UTC, FerLeiva commented on middlewares/organization.middleware.js
> +const { Organization } = require("../models");
Esto que tiene que ver con eliminar usuarios? No agregar archivos externos a la tarea al PR

2022-10-03 17:29 UTC, FerLeiva commented on migrations/20220928025535-allow-null-for-deleted-at-Category-table.js
>  module.exports = {
???

2022-10-03 17:29 UTC, FerLeiva commented on routes/organization.routes.js
Es una tarea de eliminar usuarios??

2022-10-04 00:10 UTC, opolinad commented
Se quitaron los archivos que no corresponden a la tarea

2022-10-04 13:52 UTC, FerLeiva approved these changes

2022-10-04 13:52 UTC, merged