[OT294-68]-Modificar endpoint público de organizations para devolver links de redes sociales
alkemyTech/OT294-server pull request #81
Opened 2022-10-03 22:16 UTC by JtabaresH

https://alkemy-labs.atlassian.net/browse/OT294-68

Adición de links de redes sociales a endpoint publico
![image](https://user-images.githubusercontent.com/71291097/193695753-c6219f95-3ac6-4dba-81e9-93ea5be9f65b.png)

2022-10-04 14:02 UTC, FerLeiva requested changes
Sumado a esto, el endpoint fue actualizado??

2022-10-04 14:02 UTC, FerLeiva commented on app.js
> +<<<<<<< HEAD
Mismo error!!

2022-10-04 18:37 UTC, FerLeiva commented
Juan, este sigue teniendo conflictos!

2022-10-04 19:38 UTC, JtabaresH commented
Listo Fer, ya corregí. Revisas y me comentas si esta todo ok

2022-10-05 18:10 UTC, FerLeiva approved these changes

2022-10-05 18:12 UTC, closed without merging